package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MockPermissionMenuRela generated by hbm2java
 */
@Entity
@Table(name = "MOCK_PERMISSION_MENU_RELA")
public class MockPermissionMenuRela {

	private BigDecimal id;
	private BigDecimal menuId;
	private BigDecimal permissionId;

	public MockPermissionMenuRela() {
	}

	public MockPermissionMenuRela(BigDecimal id) {
		this.id = id;
	}

	public MockPermissionMenuRela(BigDecimal id, BigDecimal menuId, BigDecimal permissionId) {
		this.id = id;
		this.menuId = menuId;
		this.permissionId = permissionId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "MENU_ID", precision = 22, scale = 0)
	public BigDecimal getMenuId() {
		return this.menuId;
	}

	public void setMenuId(BigDecimal menuId) {
		this.menuId = menuId;
	}

	@Column(name = "PERMISSION_ID", precision = 22, scale = 0)
	public BigDecimal getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(BigDecimal permissionId) {
		this.permissionId = permissionId;
	}

}
