package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MockInputOutput generated by hbm2java
 */
@Entity
@Table(name = "MOCK_INPUT_OUTPUT")
public class MockInputOutput {

	private BigDecimal ioId;
	private BigDecimal apiId;
	private String body;
	private BigDecimal mediaTypeId;
	private BigDecimal typeIoId;

	public MockInputOutput() {
	}

	public MockInputOutput(BigDecimal ioId) {
		this.ioId = ioId;
	}

	public MockInputOutput(BigDecimal ioId, BigDecimal apiId, String body, BigDecimal mediaTypeId, BigDecimal typeIoId) {
		this.ioId = ioId;
		this.apiId = apiId;
		this.body = body;
		this.mediaTypeId = mediaTypeId;
		this.typeIoId = typeIoId;
	}

	@Id
	@Column(name = "IO_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIoId() {
		return this.ioId;
	}

	public void setIoId(BigDecimal ioId) {
		this.ioId = ioId;
	}

	@Column(name = "API_ID", precision = 22, scale = 0)
	public BigDecimal getApiId() {
		return this.apiId;
	}

	public void setApiId(BigDecimal apiId) {
		this.apiId = apiId;
	}

	@Column(name = "BODY", length = 4000)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "MEDIA_TYPE_ID", precision = 22, scale = 0)
	public BigDecimal getMediaTypeId() {
		return this.mediaTypeId;
	}

	public void setMediaTypeId(BigDecimal mediaTypeId) {
		this.mediaTypeId = mediaTypeId;
	}

	@Column(name = "TYPE_IO_ID", precision = 22, scale = 0)
	public BigDecimal getTypeIoId() {
		return this.typeIoId;
	}

	public void setTypeIoId(BigDecimal typeIoId) {
		this.typeIoId = typeIoId;
	}

}
