package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MockComment generated by hbm2java
 */
@Entity
@Table(name = "MOCK_COMMENT")
public class MockComment {

	private BigDecimal id;
	private BigDecimal apiId;
	private String contentComment;
	private Date dateComment;
	private BigDecimal userId;

	public MockComment() {
	}

	public MockComment(BigDecimal id) {
		this.id = id;
	}

	public MockComment(BigDecimal id, BigDecimal apiId, String contentComment, Date dateComment, BigDecimal userId) {
		this.id = id;
		this.apiId = apiId;
		this.contentComment = contentComment;
		this.dateComment = dateComment;
		this.userId = userId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "API_ID", precision = 22, scale = 0)
	public BigDecimal getApiId() {
		return this.apiId;
	}

	public void setApiId(BigDecimal apiId) {
		this.apiId = apiId;
	}

	@Column(name = "CONTENT_COMMENT", length = 4000)
	public String getContentComment() {
		return this.contentComment;
	}

	public void setContentComment(String contentComment) {
		this.contentComment = contentComment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_COMMENT", length = 7)
	public Date getDateComment() {
		return this.dateComment;
	}

	public void setDateComment(Date dateComment) {
		this.dateComment = dateComment;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

}
