package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MockLog generated by hbm2java
 */
@Entity
@Table(name = "MOCK_LOG")
public class MockLog {

	private BigDecimal id;
	private BigDecimal contentLog;
	private Date dateCreateLog;
	private BigDecimal projectId;
	private BigDecimal userId;

	public MockLog() {
	}

	public MockLog(BigDecimal id) {
		this.id = id;
	}

	public MockLog(BigDecimal id, BigDecimal contentLog, Date dateCreateLog, BigDecimal projectId, BigDecimal userId) {
		this.id = id;
		this.contentLog = contentLog;
		this.dateCreateLog = dateCreateLog;
		this.projectId = projectId;
		this.userId = userId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "CONTENT_LOG", precision = 22, scale = 0)
	public BigDecimal getContentLog() {
		return this.contentLog;
	}

	public void setContentLog(BigDecimal contentLog) {
		this.contentLog = contentLog;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CREATE_LOG", length = 7)
	public Date getDateCreateLog() {
		return this.dateCreateLog;
	}

	public void setDateCreateLog(Date dateCreateLog) {
		this.dateCreateLog = dateCreateLog;
	}

	@Column(name = "PROJECT_ID", precision = 22, scale = 0)
	public BigDecimal getProjectId() {
		return this.projectId;
	}

	public void setProjectId(BigDecimal projectId) {
		this.projectId = projectId;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

}
