package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MockContract generated by hbm2java
 */
@Entity
@Table(name = "MOCK_CONTRACT")
public class MockContract {

	private BigDecimal contractId;
	private BigDecimal userId;

	public MockContract() {
	}

	public MockContract(BigDecimal contractId) {
		this.contractId = contractId;
	}

	public MockContract(BigDecimal contractId, BigDecimal userId) {
		this.contractId = contractId;
		this.userId = userId;
	}

	@Id
	@Column(name = "CONTRACT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getContractId() {
		return this.contractId;
	}

	public void setContractId(BigDecimal contractId) {
		this.contractId = contractId;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

}
