package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MockPermissionShare generated by hbm2java
 */
@Entity
@Table(name = "MOCK_PERMISSION_SHARE")
public class MockPermissionShare {

	private BigDecimal permissionId;

	public MockPermissionShare() {
	}

	public MockPermissionShare(BigDecimal permissionId) {
		this.permissionId = permissionId;
	}

	@Id
	@Column(name = "PERMISSION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(BigDecimal permissionId) {
		this.permissionId = permissionId;
	}
}
