package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MockRolePermissionRela generated by hbm2java
 */
@Entity
@Table(name = "MOCK_ROLE_PERMISSION_RELA")
public class MockRolePermissionRela {

	private BigDecimal id;
	private BigDecimal permissionId;
	private BigDecimal roleId;

	public MockRolePermissionRela() {
	}

	public MockRolePermissionRela(BigDecimal id) {
		this.id = id;
	}

	public MockRolePermissionRela(BigDecimal id, BigDecimal permissionId, BigDecimal roleId) {
		this.id = id;
		this.permissionId = permissionId;
		this.roleId = roleId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "PERMISSION_ID", precision = 22, scale = 0)
	public BigDecimal getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(BigDecimal permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "ROLE_ID", precision = 22, scale = 0)
	public BigDecimal getRoleId() {
		return this.roleId;
	}

	public void setRoleId(BigDecimal roleId) {
		this.roleId = roleId;
	}

}
