package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MockRoleUser generated by hbm2java
 */
@Entity
@Table(name = "MOCK_ROLE_USER")
public class MockRoleUser {

	private BigDecimal roleUserId;

	public MockRoleUser() {
	}

	public MockRoleUser(BigDecimal roleUserId) {
		this.roleUserId = roleUserId;
	}

	@Id
	@Column(name = "ROLE_USER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRoleUserId() {
		return this.roleUserId;
	}

	public void setRoleUserId(BigDecimal roleUserId) {
		this.roleUserId = roleUserId;
	}

}
