package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MockUserShare generated by hbm2java
 */
@Entity
@Table(name = "MOCK_USER_SHARE")
public class MockUserShare {

	private BigDecimal id;
	private BigDecimal roleId;
	private BigDecimal userIdInvite;
	private BigDecimal userIdReceiver;
	private BigDecimal userIdSuperInvite;

	public MockUserShare() {
	}

	public MockUserShare(BigDecimal id) {
		this.id = id;
	}

	public MockUserShare(BigDecimal id, BigDecimal roleId, BigDecimal userIdInvite, BigDecimal userIdReceiver, BigDecimal userIdSuperInvite) {
		this.id = id;
		this.roleId = roleId;
		this.userIdInvite = userIdInvite;
		this.userIdReceiver = userIdReceiver;
		this.userIdSuperInvite = userIdSuperInvite;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "ROLE_ID", precision = 22, scale = 0)
	public BigDecimal getRoleId() {
		return this.roleId;
	}

	public void setRoleId(BigDecimal roleId) {
		this.roleId = roleId;
	}

	@Column(name = "USER_ID_INVITE", precision = 22, scale = 0)
	public BigDecimal getUserIdInvite() {
		return this.userIdInvite;
	}

	public void setUserIdInvite(BigDecimal userIdInvite) {
		this.userIdInvite = userIdInvite;
	}

	@Column(name = "USER_ID_RECEIVER", precision = 22, scale = 0)
	public BigDecimal getUserIdReceiver() {
		return this.userIdReceiver;
	}

	public void setUserIdReceiver(BigDecimal userIdReceiver) {
		this.userIdReceiver = userIdReceiver;
	}

	@Column(name = "USER_ID_SUPER_INVITE", precision = 22, scale = 0)
	public BigDecimal getUserIdSuperInvite() {
		return this.userIdSuperInvite;
	}

	public void setUserIdSuperInvite(BigDecimal userIdSuperInvite) {
		this.userIdSuperInvite = userIdSuperInvite;
	}

}
