package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MockContractServiceRela generated by hbm2java
 */
@Entity
@Table(name = "MOCK_CONTRACT_SERVICE_RELA")
public class MockContractServiceRela {

	private BigDecimal id;
	private BigDecimal contractId;
	private BigDecimal serviceId;

	public MockContractServiceRela() {
	}

	public MockContractServiceRela(BigDecimal id) {
		this.id = id;
	}

	public MockContractServiceRela(BigDecimal id, BigDecimal contractId, BigDecimal serviceId) {
		this.id = id;
		this.contractId = contractId;
		this.serviceId = serviceId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "CONTRACT_ID", precision = 22, scale = 0)
	public BigDecimal getContractId() {
		return this.contractId;
	}

	public void setContractId(BigDecimal contractId) {
		this.contractId = contractId;
	}

	@Column(name = "SERVICE_ID", precision = 22, scale = 0)
	public BigDecimal getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(BigDecimal serviceId) {
		this.serviceId = serviceId;
	}

}
