package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MockMenu generated by hbm2java
 */
@Entity
@Table(name = "MOCK_MENU")
public class MockMenu {

	private BigDecimal menuId;
	private BigDecimal menuIcon;
	private String nameMenu;
	private String nameMenuVi;
	private BigDecimal parentMenu;
	private BigDecimal position;
	private BigDecimal typeMenu;

	public MockMenu() {
	}

	public MockMenu(BigDecimal menuId) {
		this.menuId = menuId;
	}

	public MockMenu(BigDecimal menuId, BigDecimal menuIcon, String nameMenu, String nameMenuVi, BigDecimal parentMenu, BigDecimal position, BigDecimal typeMenu) {
		this.menuId = menuId;
		this.menuIcon = menuIcon;
		this.nameMenu = nameMenu;
		this.nameMenuVi = nameMenuVi;
		this.parentMenu = parentMenu;
		this.position = position;
		this.typeMenu = typeMenu;
	}

	@Id
	@Column(name = "MENU_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getMenuId() {
		return this.menuId;
	}

	public void setMenuId(BigDecimal menuId) {
		this.menuId = menuId;
	}

	@Column(name = "MENU_ICON", precision = 22, scale = 0)
	public BigDecimal getMenuIcon() {
		return this.menuIcon;
	}

	public void setMenuIcon(BigDecimal menuIcon) {
		this.menuIcon = menuIcon;
	}

	@Column(name = "NAME_MENU", length = 4000)
	public String getNameMenu() {
		return this.nameMenu;
	}

	public void setNameMenu(String nameMenu) {
		this.nameMenu = nameMenu;
	}

	@Column(name = "NAME_MENU_VI", length = 4000)
	public String getNameMenuVi() {
		return this.nameMenuVi;
	}

	public void setNameMenuVi(String nameMenuVi) {
		this.nameMenuVi = nameMenuVi;
	}

	@Column(name = "PARENT_MENU", precision = 22, scale = 0)
	public BigDecimal getParentMenu() {
		return this.parentMenu;
	}

	public void setParentMenu(BigDecimal parentMenu) {
		this.parentMenu = parentMenu;
	}

	@Column(name = "POSITION", precision = 22, scale = 0)
	public BigDecimal getPosition() {
		return this.position;
	}

	public void setPosition(BigDecimal position) {
		this.position = position;
	}

	@Column(name = "TYPE_MENU", precision = 22, scale = 0)
	public BigDecimal getTypeMenu() {
		return this.typeMenu;
	}

	public void setTypeMenu(BigDecimal typeMenu) {
		this.typeMenu = typeMenu;
	}

}
