package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MockMediaType generated by hbm2java
 */
@Entity
@Table(name = "MOCK_MEDIA_TYPE")
public class MockMediaType {

	private BigDecimal mediaTypeId;
	private String name;
	private String value;

	public MockMediaType() {
	}

	public MockMediaType(BigDecimal mediaTypeId) {
		this.mediaTypeId = mediaTypeId;
	}

	public MockMediaType(BigDecimal mediaTypeId, String name, String value) {
		this.mediaTypeId = mediaTypeId;
		this.name = name;
		this.value = value;
	}

	@Id
	@Column(name = "MEDIA_TYPE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getMediaTypeId() {
		return this.mediaTypeId;
	}

	public void setMediaTypeId(BigDecimal mediaTypeId) {
		this.mediaTypeId = mediaTypeId;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "VALUE", length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
