package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1


import globaldefine.Config;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


import com.viettel.data.query.MockTokenQuery;

/**
 * MockToken generated by hbm2java
 */

@Entity
@javax.persistence.NamedNativeQueries({
		@javax.persistence.NamedNativeQuery(name = MockTokenQuery.GET_ALL_TOKEN_NAME, query = MockTokenQuery.GET_ALL_TOKEN, resultClass = MockToken.class, hints = @javax.persistence.QueryHint(name = Config.callable, value = "true")),
		@javax.persistence.NamedNativeQuery(name = MockTokenQuery.GET_TOKEN_BY_USER_ID_NAME, query = MockTokenQuery.GET_TOKEN_BY_USER_ID_QUERY, resultClass = MockToken.class, hints = @javax.persistence.QueryHint(name = Config.callable, value = "true")), })
@Table(name = "MOCK_TOKEN")
public class MockToken {

	private Long tokenId;
	private Long userId;
	private String fullTokenString;
	private Long startTime;
	private String tokenString;
	

	public MockToken() {
	}

	public MockToken(Long tokenId) {
		this.tokenId = tokenId;
	}

	public MockToken(Long tokenId, Long userId, String fullTokenString, Long startTime) {
		this.tokenId = tokenId;
		this.userId = userId;
		this.fullTokenString = fullTokenString;
		this.startTime = startTime;
	}

	
	@Column(name = "TOKEN_ID", precision = 22, scale = 0)
	public Long getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(Long tokenId) {
		this.tokenId = tokenId;
	}
	
	@Id
	@Column(name = "USER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "FULL_TOKEN_STRING", length = 500)
	public String getFullTokenString() {
		return this.fullTokenString;
	}

	public void setFullTokenString(String fullTokenString) {
		this.fullTokenString = fullTokenString;
	}

	@Column(name = "START_TIME", precision = 22, scale = 0)
	public Long getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}
	
	@Column(name = "TOKEN_STRING", length = 50)
	public String getTokenString() {
		return this.tokenString;
	}

	public void setTokenString(String tokenString) {
		this.tokenString = tokenString;
	}

}