package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MockPrice generated by hbm2java
 */
@Entity
@Table(name = "MOCK_PRICE")
public class MockPrice {

	private BigDecimal priceId;
	private BigDecimal value;

	public MockPrice() {
	}

	public MockPrice(BigDecimal priceId) {
		this.priceId = priceId;
	}

	public MockPrice(BigDecimal priceId, BigDecimal value) {
		this.priceId = priceId;
		this.value = value;
	}

	@Id
	@Column(name = "PRICE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getPriceId() {
		return this.priceId;
	}

	public void setPriceId(BigDecimal priceId) {
		this.priceId = priceId;
	}

	@Column(name = "VALUE", precision = 22, scale = 0)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

}
