package com.viettel.data.model.entity;

// Generated Aug 6, 2015 9:16:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MockTypeIo generated by hbm2java
 */
@Entity
@Table(name = "MOCK_TYPE_IO")
public class MockTypeIo {

	private BigDecimal typeIoId;
	private BigDecimal name;

	public MockTypeIo() {
	}

	public MockTypeIo(BigDecimal typeIoId) {
		this.typeIoId = typeIoId;
	}

	public MockTypeIo(BigDecimal typeIoId, BigDecimal name) {
		this.typeIoId = typeIoId;
		this.name = name;
	}

	@Id
	@Column(name = "TYPE_IO_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getTypeIoId() {
		return this.typeIoId;
	}

	public void setTypeIoId(BigDecimal typeIoId) {
		this.typeIoId = typeIoId;
	}

	@Column(name = "NAME", precision = 22, scale = 0)
	public BigDecimal getName() {
		return this.name;
	}

	public void setName(BigDecimal name) {
		this.name = name;
	}

}
